#!/bin/bash
#SBATCH --job-name=3d_rgc_testing
#SBATCH --output=/home/akaur101/data/3d_data/testing_outputs/3d_rgc_testing_v3_≈%j.stdout
#SBATCH --partition dept.appliedmath
#SBATCH --gres=gpu:2
#SBATCH --time=48:00:00

#SBATCH --mail-user=akaur101@ucmerced.edu
#SBATCH --mail-type=BEGIN
#SBATCH --mail-type=END
#SBATCH --mail-type=FAIL
#SBATCH --mail-type=ALL
#SBATCH --export=ALL

module load anaconda3
source activate env_pytorch
python /home/akaur101/data/3d_data/3d_rgc_testing.py /home/akaur101/data/3d_data/Fluo-C3DH-A549/01/ /home/akaur101/data/3d_data/Fluo-C3DH-A549/01_GT/SEG/ 

